#!/usr/bin/env bash

# Test that `example/run-tests` exits with success when expected and, more importantly, that it
# exits with an error on failure. This test does not use the enyx-regtest framework for the pretty
# obvious reason that if a bug were to cause the framework to ignore errors, this test might then
# fail to properly report errors as well.

set -euo pipefail

cd example

echo Running good tests...
echo ---------------------
./run-tests --exclude '*-fail'

echo
echo Running bad tests...
echo --------------------
for t in $(./run-tests -l '*-fail'); do
    ./run-tests "$t" && { echo Was expecting failure!; exit 1; }
done

echo
echo Running all tests...
echo --------------------
./run-tests && { echo Was expecting failure!; exit 1; }

echo
echo OK
exit 0
