#!/usr/bin/env bash

# = Silly GNU Grep Tests

# Note: Purposefully contains some failing tests.

set -eu

[[ -n "${ENYX_REGTEST_DIR-}" ]] || ENYX_REGTEST_DIR=../../lib

: ${REGTEST_SUITE_TIMEOUT=5s}

. "$ENYX_REGTEST_DIR"/run-tests.sh

eval "${REGTEST_EXAMPLE_EXTRA_SETUP-}"

if [[ -z "${REGTEST_EXAMPLE_SUITE_FILES-}" ]]; then
    regtest_run_suites tests \
        ascii \
        unicode
else
    regtest_run_suites tests $REGTEST_EXAMPLE_SUITE_FILES
fi
